workflows:
  flutter-app:
    name: Get Work App Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_BUILD_NAME: "1.0.0"
        FLUTTER_BUILD_NUMBER: "1"
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Build iOS
        script: |
          flutter build ipa --release --no-codesign

      - name: Build Android
        script: |
          flutter build apk --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/app/outputs/flutter-apk/*.apk
