name: get_work_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  url_launcher: ^6.2.2
  path_provider: ^2.1.1
  pdfrx: ^1.0.2
  image: ^4.1.3
  photo_view: ^0.14.0
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  http: ^1.4.0
  flutter_dotenv: ^5.1.0
  open_file: ^3.5.10
  intl: ^0.20.2
  cloudinary: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env